#include "web_api.h"
#include <ArduinoJson.h>
#include <WiFi.h>

extern const char INDEX_HTML[] PROGMEM;
static String uidText(const uint8_t*u){String s;for(int i=7;i>=0;i--){if(u[i]<16)s+='0';s+=String(u[i],HEX);if(i)s+=':';}s.toUpperCase();return s;}
static const char* roleName(RF430::ChannelRole r){return r==RF430::ChannelRole::Sensor?"sensor":r==RF430::ChannelRole::Reference?"reference":"ignore";}
static const char* filterName(RF430::AdcFilter f){return f==RF430::AdcFilter::CIC?"cic":"moving_average";}
static void adcJson(JsonObject o,const AdcConfig&a,bool en){o["enabled"]=en;o["gain"]=1<<uint8_t(a.gain);o["filter"]=filterName(a.filter);o["rate"]=a.rate;o["reference"]=a.reference==RF430::AdcReference::SVSS?"svss":"avss";uint8_t v;encodeAdcConfig(a,v);o["byte"]=v;}

WebApi::WebApi(RF430Device&d,MeasurementService&m,MeasurementConfig&c,SettingsStore&s):device_(d),measurement_(m),config_(c),store_(s){}
String WebApi::statusJson(){JsonDocument d;d["pn5180"]=true;d["rf430"]=device_.detected();d["uid"]=device_.detected()?uidText(device_.uid()):"";d["block_size"]=device_.blockSize();d["block_count"]=device_.blockCount();d["sampling"]=measurement_.busy();d["ip"]=WiFi.softAPIP().toString();String s;serializeJson(d,s);return s;}
String WebApi::configJson(){JsonDocument d;adcJson(d["adc1"].to<JsonObject>(),config_.adc1,config_.adc1Enabled);adcJson(d["adc2"].to<JsonObject>(),config_.adc2,config_.adc2Enabled);adcJson(d["adc0"].to<JsonObject>(),config_.adc0,config_.adc0Enabled);d["adc1_role"]=roleName(config_.adc1Role);d["adc2_role"]=roleName(config_.adc2Role);d["reference_ohm"]=config_.referenceOhm;d["r0_ohm"]=config_.r0Ohm;d["gauge_factor"]=config_.gaugeFactor;d["frequency"]=config_.frequency;d["passes"]=config_.passes;d["averaging"]=config_.averaging;d["infinite"]=config_.infinite;d["resistive_bias"]=config_.resistiveBias;String s;serializeJson(d,s);return s;}
String WebApi::resultJson(const MeasurementResult&r){JsonDocument d;d["timestamp_ms"]=r.timestampMs;d["valid"]=r.valid;d["error"]=r.error;d["adc1_raw"]=r.adc1Raw;d["adc2_raw"]=r.adc2Raw;d["adc0_raw"]=r.adc0Raw;d["sensor_ohm"]=r.sensorResistance;d["r0_ohm"]=r.r0;d["delta_r_ohm"]=r.deltaR;d["relative_change"]=r.relativeDelta;d["strain_ue"]=r.strain;String s;serializeJson(d,s);return s;}
String WebApi::previewJson(){uint8_t b0[8],cur[8]={0,0,0,5,0,255,255,255},b2[8];buildBlock0(config_,false,b0);buildBlock2(config_,cur,b2);JsonDocument d;JsonArray a=d["block0"].to<JsonArray>(),b=d["block2"].to<JsonArray>();for(int i=0;i<8;i++){a.add(b0[i]);b.add(b2[i]);}String s;serializeJson(d,s);return s;}
static RF430::ChannelRole parseRole(const char*s){return !strcmp(s,"sensor")?RF430::ChannelRole::Sensor:!strcmp(s,"reference")?RF430::ChannelRole::Reference:RF430::ChannelRole::Ignore;}
static bool parseAdc(JsonObjectConst o,AdcConfig&a,bool&e){e=o["enabled"]|e;int g=o["gain"]|(1<<uint8_t(a.gain));a.gain=g==8?RF430::AdcGain::X8:g==4?RF430::AdcGain::X4:g==2?RF430::AdcGain::X2:RF430::AdcGain::X1;String f=o["filter"]|filterName(a.filter);a.filter=f=="moving_average"?RF430::AdcFilter::MovingAverage:RF430::AdcFilter::CIC;a.rate=o["rate"]|a.rate;String r=o["reference"]|(a.reference==RF430::AdcReference::SVSS?"svss":"avss");a.reference=r=="avss"?RF430::AdcReference::AVSS:RF430::AdcReference::SVSS;return true;}
bool WebApi::updateConfig(const String&body,String&e){JsonDocument d;if(deserializeJson(d,body)){e="invalid JSON";return false;}if(d["adc1"].is<JsonObject>())parseAdc(d["adc1"],config_.adc1,config_.adc1Enabled);if(d["adc2"].is<JsonObject>())parseAdc(d["adc2"],config_.adc2,config_.adc2Enabled);if(d["adc0"].is<JsonObject>())parseAdc(d["adc0"],config_.adc0,config_.adc0Enabled);if(!d["adc1_role"].isNull())config_.adc1Role=parseRole(d["adc1_role"]);if(!d["adc2_role"].isNull())config_.adc2Role=parseRole(d["adc2_role"]);config_.referenceOhm=d["reference_ohm"]|config_.referenceOhm;config_.r0Ohm=d["r0_ohm"]|config_.r0Ohm;config_.gaugeFactor=d["gauge_factor"]|config_.gaugeFactor;config_.frequency=d["frequency"]|config_.frequency;config_.passes=d["passes"]|config_.passes;config_.averaging=d["averaging"]|config_.averaging;config_.infinite=d["infinite"]|config_.infinite;config_.resistiveBias=d["resistive_bias"]|config_.resistiveBias;return validateMeasurementConfig(config_,e);}
void WebApi::addHistory(const MeasurementResult&r){history_[head_]=r;head_=(head_+1)%HISTORY;if(count_<HISTORY)count_++;}
String WebApi::csv(){String s="timestamp_ms,adc1_raw,adc2_raw,adc0_raw,resistance_ohm,r0_ohm,delta_r_ohm,relative_change,strain_ue,valid\n";for(size_t i=0;i<count_;i++){const auto&r=history_[(head_+HISTORY-count_+i)%HISTORY];s+=String(r.timestampMs)+","+r.adc1Raw+","+r.adc2Raw+","+r.adc0Raw+","+String(r.sensorResistance,4)+","+String(r.r0,4)+","+String(r.deltaR,4)+","+String(r.relativeDelta,9)+","+String(r.strain,3)+","+(r.valid?"1":"0")+"\n";}return s;}
void WebApi::begin(){
 server_.on("/",HTTP_GET,[](AsyncWebServerRequest*r){r->send_P(200,"text/html; charset=utf-8",INDEX_HTML);});
 server_.on("/api/status",HTTP_GET,[this](AsyncWebServerRequest*r){r->send(200,"application/json",statusJson());});
 server_.on("/api/config",HTTP_GET,[this](AsyncWebServerRequest*r){r->send(200,"application/json",configJson());});
 server_.on("/api/preview",HTTP_GET,[this](AsyncWebServerRequest*r){r->send(200,"application/json",previewJson());});
 server_.on("/api/scan",HTTP_POST,[this](AsyncWebServerRequest*r){bool ok=device_.detect();r->send(ok?200:503,"application/json",statusJson());});
 server_.on("/api/reset",HTTP_POST,[this](AsyncWebServerRequest*r){bool ok=device_.resetReader();r->send(ok?200:503,"application/json",statusJson());});
 server_.on("/api/apply",HTTP_POST,[this](AsyncWebServerRequest*r){bool ok=device_.detected()&&device_.applyConfig(config_);r->send(ok?200:503,"application/json",ok?"{\"ok\":true}":"{\"ok\":false}");});
 server_.on("/api/sample",HTTP_POST,[this](AsyncWebServerRequest*r){bool ok=measurement_.beginSingle(config_);r->send(ok?202:409,"application/json",ok?"{\"started\":true}":"{\"started\":false}");});
 server_.on("/api/start",HTTP_POST,[this](AsyncWebServerRequest*r){continuous_=true;nextSample_=0;r->send(202,"application/json","{\"continuous\":true}");});
 server_.on("/api/stop",HTTP_POST,[this](AsyncWebServerRequest*r){continuous_=false;measurement_.cancel();r->send(200,"application/json","{\"continuous\":false}");});
 server_.on("/api/baseline",HTTP_POST,[this](AsyncWebServerRequest*r){if(measurement_.last().valid)config_.r0Ohm=measurement_.last().sensorResistance;store_.save(config_);r->send(200,"application/json",configJson());});
 server_.on("/api/export.csv",HTTP_GET,[this](AsyncWebServerRequest*r){AsyncWebServerResponse*x=r->beginResponse(200,"text/csv",csv());x->addHeader("Content-Disposition","attachment; filename=rf430.csv");r->send(x);});
 server_.on("/api/block",HTTP_GET,[this](AsyncWebServerRequest*r){int id=r->hasParam("id")?r->getParam("id")->value().toInt():-1;if(id<0||id>15){r->send(400,"application/json","{\"error\":\"block 0..15 only\"}");return;}uint8_t b[8];if(!device_.readBlock(id,b)){r->send(503,"application/json","{\"error\":\"read failed\"}");return;}JsonDocument d;d["id"]=id;JsonArray a=d["bytes"].to<JsonArray>();for(auto v:b)a.add(v);String s;serializeJson(d,s);r->send(200,"application/json",s);});
 server_.on("/api/config",HTTP_POST,[](AsyncWebServerRequest*){},nullptr,[this](AsyncWebServerRequest*r,uint8_t*d,size_t l,size_t,size_t){String body;body.reserve(l);for(size_t i=0;i<l;i++)body+=(char)d[i];String e;if(!updateConfig(body,e)){r->send(400,"application/json","{\"error\":\""+e+"\"}");return;}store_.save(config_);r->send(200,"application/json",configJson());});
 events_.onConnect([](AsyncEventSourceClient*c){c->send("{\"connected\":true}","status",millis());});server_.addHandler(&events_);server_.begin();
}
void WebApi::publish(const MeasurementResult&r){addHistory(r);String s=resultJson(r);events_.send(s.c_str(),"measurement",r.timestampMs);}
void WebApi::loop(){MeasurementResult r;if(measurement_.poll(config_,r)){if(r.valid)Serial.printf("ADC1=%u ADC2=%u ADC0=%u Rref=%.2f ohm Rsensor=%.2f ohm\n",r.adc1Raw,r.adc2Raw,r.adc0Raw,config_.referenceOhm,r.sensorResistance);else Serial.printf("Measurement failed: %s\n",r.error.c_str());publish(r);nextSample_=millis()+250;}if(continuous_&&!measurement_.busy()&&millis()>=nextSample_){if(!device_.detected())device_.detect();if(!measurement_.beginSingle(config_)){events_.send("{\"rf430\":false}","status",millis());nextSample_=millis()+1000;}}}
