#include <Arduino.h>
#define const extern const
const char INDEX_HTML[] PROGMEM=R"HTML(<!doctype html><html lang=zh-CN><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>RF430 Tool</title><style>
*{box-sizing:border-box}body{margin:0;background:#07111a;color:#e8f4f8;font:14px system-ui}.w{max-width:1100px;margin:auto;padding:22px}header{display:flex;justify-content:space-between}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px}.c{grid-column:span 4;background:#101f2b;border:1px solid #294354;border-radius:14px;padding:15px}.wide{grid-column:span 8}.full{grid-column:1/-1}h2{font-size:14px;color:#56d8c7}.metric{font-size:27px;font-weight:bold}.muted{color:#92a8b6}label{display:block;margin-top:7px}input,select,button{background:#08151e;color:#eef;border:1px solid #36566b;border-radius:7px;padding:7px}input,select{width:100%}button{margin:6px 3px 0 0;cursor:pointer}.primary{background:#167b73}.chs{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.ch{padding:9px;border:1px solid #294354;border-radius:8px}pre{white-space:pre-wrap;color:#bce9df}canvas{width:100%;height:220px;background:#08151e}@media(max-width:750px){.c,.wide{grid-column:1/-1}.chs{grid-template-columns:1fr}}</style></head><body><div class=w><header><div><h1>RF430 Sensor Lab</h1><p class=muted>ESP32-C3 + PN5180</p></div><b id=dev>Connecting…</b></header><main class=grid>
<section class=c><h2>DEVICE</h2><div id=uid>UID —</div><p id=blocks class=muted>—</p><button onclick="post('/api/scan')">Scan</button><button onclick="post('/api/reset')">Reset</button></section>
<section class=c><h2>MEASUREMENT</h2><div id=res class=metric>— Ω</div><div id=raw class=muted>ADC1 — · ADC2 —</div><p id=strain>ΔR — · strain —</p><button class=primary onclick="post('/api/sample')">Single</button><button onclick="post('/api/start')">Continuous</button><button onclick="post('/api/stop')">Stop</button><button onclick="post('/api/baseline')">Set R0</button><button onclick="location='/api/export.csv'">CSV</button></section>
<section class=c><h2>CONTROL</h2><label>Reference Ω<input id=rref type=number></label><label>R0 Ω<input id=r0 type=number></label><label>Gauge Factor<input id=gf type=number step=.01></label><label>Passes<input id=passes type=number min=1 max=2047></label><label>ROM Averaging<input id=avg type=number min=1 max=255></label><label><input id=bias type=checkbox style="width:auto"> Resistive Bias</label></section>
<section class="c wide"><h2>ADC CONFIGURATION</h2><div class=chs id=channels></div><button class=primary onclick=save()>Save</button><button onclick="post('/api/apply')">Apply to RF430</button><button onclick=preset()>Working Preset</button><pre id=preview></pre></section>
<section class=c><h2>RAW BLOCK (READ ONLY)</h2><input id=bid value=9 type=number min=0 max=15><button onclick=readBlock()>Read</button><pre id=block>—</pre></section><section class="c full"><h2>LIVE RESISTANCE</h2><canvas id=chart width=1050 height=220></canvas></section></main></div><script>
const $=x=>document.getElementById(x),ns=['adc1','adc2','adc0'];let pts=[];function html(n){return `<div class=ch><b>${n.toUpperCase()}</b><label><input id=${n}e type=checkbox style="width:auto"> Enable</label><label>Gain<select id=${n}g>${[1,2,4,8].map(x=>`<option>${x}</option>`)}</select></label><label>Filter<select id=${n}f onchange="rates('${n}')"><option value=cic>CIC</option><option value=moving_average>Moving Average</option></select></label><label>Rate<select id=${n}rate></select></label><label>Reference<select id=${n}ref><option>svss</option><option>avss</option></select></label>${n!='adc0'?`<label>Role<select id=${n}role><option>sensor</option><option>reference</option><option>ignore</option></select></label>`:''}</div>`}$('channels').innerHTML=ns.map(html).join('');function rates(n,v){let a=$(n+'f').value=='cic'?[32,64,128,256,512,1024,2048]:[4096,8192,16384,32768];$(n+'rate').innerHTML=a.map(x=>`<option ${x==v?'selected':''}>${x}</option>`).join('')}ns.forEach(n=>rates(n));
async function post(u){let r=await fetch(u,{method:'POST'});if(!r.ok)alert(await r.text());setTimeout(refresh,100)}async function refresh(){let s=await fetch('/api/status').then(r=>r.json());$('dev').textContent=s.rf430?'RF430 ONLINE':'RF430 ABSENT';$('uid').textContent='UID '+(s.uid||'—');$('blocks').textContent=`${s.block_size||'—'} bytes × ${s.block_count||'—'} blocks · ${s.ip}`;preview()}
async function load(){let c=await fetch('/api/config').then(r=>r.json());ns.forEach(n=>{let a=c[n];$(n+'e').checked=a.enabled;$(n+'g').value=a.gain;$(n+'f').value=a.filter;rates(n,a.rate);$(n+'ref').value=a.reference});$('adc1role').value=c.adc1_role;$('adc2role').value=c.adc2_role;$('rref').value=c.reference_ohm;$('r0').value=c.r0_ohm;$('gf').value=c.gauge_factor;$('passes').value=c.passes;$('avg').value=c.averaging;$('bias').checked=c.resistive_bias}function payload(){let o={reference_ohm:+$('rref').value,r0_ohm:+$('r0').value,gauge_factor:+$('gf').value,passes:+$('passes').value,averaging:+$('avg').value,resistive_bias:$('bias').checked,adc1_role:$('adc1role').value,adc2_role:$('adc2role').value};ns.forEach(n=>o[n]={enabled:$(n+'e').checked,gain:+$(n+'g').value,filter:$(n+'f').value,rate:+$(n+'rate').value,reference:$(n+'ref').value});return o}async function save(){let r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});if(!r.ok)alert(await r.text());preview()}
function preset(){$('adc1e').checked=$('adc2e').checked=true;$('adc0e').checked=false;['adc1','adc2'].forEach(n=>{$(n+'g').value=1;$(n+'f').value='cic';rates(n,256);$(n+'ref').value='svss'});$('adc1role').value='sensor';$('adc2role').value='reference';$('rref').value=200000;$('passes').value=$('avg').value=1;$('bias').checked=true;save()}async function preview(){let p=await fetch('/api/preview').then(r=>r.json()),h=a=>a.map(x=>x.toString(16).padStart(2,'0')).join(' ').toUpperCase();$('preview').textContent='Block 0: '+h(p.block0)+'\nBlock 2: '+h(p.block2)}async function readBlock(){let j=await fetch('/api/block?id='+$('bid').value).then(r=>r.json());$('block').textContent=j.bytes?j.bytes.map(x=>x.toString(16).padStart(2,'0')).join(' ').toUpperCase():j.error}
function draw(){let c=$('chart'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);if(pts.length<2)return;let y=pts.map(p=>p.sensor_ohm),mn=Math.min(...y),mx=Math.max(...y);if(mx==mn)mx++;x.strokeStyle='#56d8c7';x.lineWidth=2;x.beginPath();pts.forEach((p,i)=>{let a=i/(pts.length-1)*c.width,b=c.height-(p.sensor_ohm-mn)/(mx-mn)*(c.height-20)-10;i?x.lineTo(a,b):x.moveTo(a,b)});x.stroke()}let es=new EventSource('/events');es.addEventListener('measurement',e=>{let m=JSON.parse(e.data);if(m.valid){$('res').textContent=m.sensor_ohm.toFixed(2)+' Ω';$('raw').textContent=`ADC1 ${m.adc1_raw} · ADC2 ${m.adc2_raw}`;$('strain').textContent=`ΔR ${m.delta_r_ohm.toFixed(3)} Ω · strain ${m.strain_ue.toFixed(2)} με`;pts.push(m);if(pts.length>500)pts.shift();draw()}else $('res').textContent=m.error});load();refresh();setInterval(refresh,3000);
</script></body></html>)HTML";
